export default {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  DELETE: "DELETE",
  RESET: "RESET",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  HANDLE_CHANGE_TODO: "HANDLE_CHANGE_TODO",
  GET_DATA: "GET_DATA",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILED: "GET_DATA_FAILED"
};
